### ISSUE TITLE
How to implement CTC 

### ISSUE THREAD

**Issue by holianh** [david-leon/Dandelion#3]
How to implement CTC for all of your NET for speech recognition?
I am trying to imagine but you do not give examples so it is very hard to understand.
Thanks for your distribute
tuananhktmt@gmail.com

**Comment by david-leon** [comment]
Dandelion has a built-in CTC implementation itself, check the [documentation here](https://david-leon.github.io/Dandelion/dandelion_objective/)

**Comment by holianh** [comment]
Thank you!
I would prefer if you write a small example below the standard documents.
